### PR TITLE
Move SuppressForbidden annotation to oshi-core

### PR DESCRIPTION
**Pull request by Palak4620**
updated changes as told, let me know if I had done something wrong.

### CODE REVIEW

**Comment by dbwiddis** [comment]
> updated changes as told, let me know if I had done something wrong.

Yep. :-)

First off, you don't need to create a new PR to respond to a code review. You can keep pushing to the same branch you created your PR from, and it will update your PR.

1. You still need to change the places in the `oshi-demo` project where the annotation is referenced, or that project won't compile.  If you are programming with an IDE it will usually mark those in red.  https://github.com/search?q=repo%3Aoshi%2Foshi%20oshi.demo.annotation&type=code

2. You need a `package-info.java` file in the new `oshi.annotations` package.   You just deleted the old one rather than "moving" it.

You should be able to run maven commands locally to test before you push:
 - `./mvnw checkstyle:check` will check for various issues (like the missing package.info).  If they are formatting related, `./mvnw checkstyle:apply` will fix them.
 - `./mvnw compile forbiddenapis:check` will be what you'll want to be using when you get to actually forbidding the API per the issue
 - `./mvnw test` will run tests

**Comment by Palak4620** [comment]
Sorry for inconvenience. I will try my best to solve this issue.

**Comment by dbwiddis** [comment]
Hey @Palak4620 since it looked like you were stalled on this, someone else stepped up and handled this in #2477.  Thank you for your contribution and sorry it ended up a bit more challenging!

**Comment by Palak4620** [comment]
thank you for this opportunity. and sorry I couldn't complete it.

**Comment by dbwiddis** [comment]
No worries, maybe try something else in the future!

**Pull request closed without merging**
