### PR TITLE
resolves #702 and #717

### LINKED ISSUE #702: Refactor Linux version parsing
I'm marking this issue for [first-timers-only](https://www.firsttimersonly.com/).  That means that I will only accept a PR for this one from someone who's never contributed to open source before. This one is easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). I'll hold your hand through this if you need me to. :-) Here are the steps to get a PR merged here.

- [ ] Read the [CONTRIBUTING](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md) file for reference.  I'll walk you through anything you don't understand.
- [ ] Find the [LinuxOSVersionInfoEx.java](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/software/os/linux/LinuxOSVersionInfoEx.java) class.
- [ ] Look at lines 149, 165, 213, 219, and 222 which reduce the String to the value between quotation marks.
- [ ] Find the [ParseUtil.java](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/util/ParseUtil.java) class.
- [ ] Create a method similar to `getSingleQuoteStringValue()` which parses Double Quotes.  
- [ ] Optionally, refactor `getSingleQuoteStringValue()` and your new method to use `getStringBetween()` which is more efficient than the `split()`.
- [ ] Write a test for the new method in the [ParseUtilTest.java](https://github.com/oshi/oshi/blob/master/oshi-core/src/test/java/oshi/util/ParseUtilTest.java) class.
- [ ] Replace the code in the 5 lines above to call the new method.
- [ ] Fork the project, commit your changes to your fork, create a PR, and get it merged
- [ ] Celebrate

### PR DESCRIPTION
**Pull request by shanmukhateja**
Resolve issue with `mvn test` fails with error `Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter` #717 

Also, resolve Linux version parsing issue #702

### CODE REVIEW

**Comment by dbwiddis** [comment]
Thanks! I really appreciate you going the extra mile to solve this.   I'd appreciate it if you can reduce this PR just to fixing the maven tests, however, as I am using the `first-timers-only` tag to help walk through other first time contributors and someone else has already "claimed" the issue to work on -- I'd like to give them time to complete the patch.

Also note on the issue that there may be other ways of fixing it, I'm not sure which is preferred but it may require a little more research.

**Comment by shanmukhateja** [comment]
Oh well I checked the Assignees list on the issue and I see it was empty so I thought of working on it. I am also a first-timer on contributing to open source projects. 
Since it has been claimed, I will respect the person's wishes. 

> I'd appreciate it if you can reduce this PR just to fixing the maven tests

So would you like me to work only on `oshi-core/src/test/java/oshi/util/ParseUtilTest.java ` ?

**Comment by dbwiddis** [comment]
> Oh well I checked the Assignees list on the issue and I see it was empty

Sorry, the first comment said: "Hi Db, I'm new to this whole contribution thing so is there anywhere I assign this issue to myself." and I replied, "In the upper right corner of this page, just above the labels, is an assignment section. You're welcome to assign it to yourself, although now that you've stated so in the comments, it's likely others will know you're working on it as well!"  Unfortunately I guess I was wrong and I'll try to use that assignment feature in the future!

> would you like me to work only on oshi-core/src/test/java/oshi/util/ParseUtilTest.java ?

Not my intent.  What I had wanted was for you to just try to fix #717 which is apparently an issue with the maven surefire plugin  I'm not sure the best solution but think upgrading the surefire version (which fixes the bug) may be the best choice, rather than the other workarounds proposed on the internet.

That said and returning to parsing, which was your original proposal: the other user's code was submitted as PR #720.  I do welcome you, if you like, to improve on that code (once it's merged, hopefully soon) by removing the intermediate "parseSingle..." and "parseDouble..." and just call the `getStringBetween` method from anywhere in the code that the other parsing is done.  

Issues #696 and #418 also can be slightly more challenging first-timer projects but I'm happy to walk you through them if you'd like!

**Comment by dbwiddis** [comment]
As mentioned, #720 and #722 have resolved #717 and #702 respectively so I'll close this PR, but do please feel free to contribute elsewhere!

**Pull request closed without merging**
