### PR TITLE
Add annotations @Documented

### PR DESCRIPTION
**Pull request by Mskat**
Add annotations in oshi.annotation.concurrent package

### CODE REVIEW

**Comment by Mskat** [comment]
Add annotations in oshi.annotation.concurrent package

**Comment by dbwiddis** [comment]
Hi @Mskat, thanks for the contribution to open source! This is exactly what needed to be done.   I had been waiting for @bob160 to work through it, but I suppose I can still work with him to find another contribution....

**Comment by Mskat** [comment]
Hi @dbwiddis and @Bob160, sorry for stealing the issue :) I'm kind of new to this stuff:) So in the future, should I always ask for an assignment first? Thank you! :)

**Comment by dbwiddis** [comment]
It's fine, it's a learning experience!  The main goal is to help new (to github) users learn how to fork, clone, push, and create pull requests so it's less important *what* you do as that you do it.   I had "assigned" the issue to Bob160 but he was also taking some time to do it... not really a big deal though!

**Comment by Mskat** [comment]
It's a really cool experience :) I'm glad I finally tried it!

**Pull request merged**
