### PR TITLE
LinuxOSProcess#getOpenFiles returns one more than expected #1608

### PR DESCRIPTION
**Pull request by slaha**
An attempt to fix https://github.com/oshi/oshi/issues/1608

### CODE REVIEW

**Review by dbwiddis — APPROVED** [review]
This looks great!   

While this fixes this specific bug, there's some repetition in the `ProcessStat` file for multiple methods that fetch a list of numeric files.  I was just doing this (unaware you were doing it) and the result is in https://github.com/dbwiddis/oshi/commit/7887bd33bb714acb09ca276d2a41f11fbe9df07b ... take a look and see if you can do the same?

**Comment by dbwiddis** [comment]
(Actually in my commit, the thread list missed excluding the process itself from the list, so that'd need to also be updated, if you're up to it.)

**Comment by slaha** [comment]
@dbwiddis I will take a look at this

**Review by dbwiddis — APPROVED** [review]
Looks great.  I'll merge after the CI tests complete.

**Comment by dbwiddis** [comment]
Oops, one more request: can you make a change log entry? :)

**Comment by slaha** [comment]
Done (at least I hope so)

**Comment by dbwiddis** [comment]
Thanks for the bug report and fix!

**Pull request merged**
