### PR TITLE
Change linux swapin/swapout counters to read only swaps

### PR DESCRIPTION
**Pull request by Roeezz**
-Change Linux virtual memory to use pswpin and pswap out instead of pgpgin and pgpgout.
-Change Solaris virtual memory to use pgswpin and pgswap out instead of pgpgin and pgpgout.

As requested in #1223

### CODE REVIEW

**Comment by Roeezz** [comment]
What did I fail?

**Comment by dbwiddis** [comment]
It's just failing because of merge conflicts with the master branch with the change log.  Click on "Resolve conflicts" and edit appropriately to put things in the right order.

**Comment by Roeezz** [comment]
Ok done, thanks for the help.

**Comment by dbwiddis** [comment]
Looks good! I'll merge once the tests finish!

**Comment by Roeezz** [comment]
Cool. Looks like other then writing test messages which I'll try to do if I have time, there isn't much coding work I can help you with. It all seems a bit too high a level for me, though I'll be glad to help with anything I can. Thanks for the opportunity.

**Comment by dbwiddis** [comment]
Yeah, it's in a pretty good state right now.  There are some long methods that could be refactored, and some parsing internal to classes that could be moved out to a "driver" class, but I've been doing that as I change things rather than trying to overhaul the whole thing.

If you want a fun challenge, see if you can commit this same fix to the 4.X branch!  (Don't bother with the changelog there.)

**Comment by Roeezz** [comment]
I could do that. But what's the challenge in there?

**Comment by dbwiddis** [comment]
Learning how to cherry-pick! :)

**Pull request merged**
