### PR TITLE
Disallow imports not on module path

### LINKED ISSUE #1799: Block imports not on module path
We want to avoid importing classes to the project from any packages not included as top-level dependencies (which are also included in the module descriptor for the java11 branch).  This aligns with the Java Modules need for an explicit `requires transitive` statement from these dependencies, and helps keep surprises with java11 releases to a minimum.

Consider the below maven plugin if it's easy to use, or find another way to block imports that aren't explicitly listed as dependencies in the pom, or specifically included (with associated `requires transitive` statement).

> Use this -> https://github.com/skuzzle/restrict-imports-enforcer-rule, works well to block the import usage.  You could also block junit4 as well as noted.
> 
> _Originally posted by @hazendaz in https://github.com/oshi/oshi/issues/1794#issuecomment-978969292_

### PR DESCRIPTION
**Pull request by dbwiddis**
Fixes #1799 

(Aside: I don't know why my formatter adds a space inside wrapped XML comments and have spent more time than I would care to trying to fix that, and failing.)

### CODE REVIEW

**Review by mprins — COMMENTED** [review]
+0 It seems like a lot of work, and it still won't catch the case where a fully qualified classname is used in the code (and thus no import)

I've never used the [banTransitiveDependencies](http://maven.apache.org/enforcer/enforcer-rules/banTransitiveDependencies.html) but it seems like that would catch most of this as well.

**Comment by dbwiddis** [comment]
> +0 It seems like a lot of work

Well I've already done the work, heh.

> and it still won't catch the case where a fully qualified classname is used in the code (and thus no import)

Yeah, but hopefully that'll be a bit more obvious to us when reviewing code. 

> I've never used the [banTransitiveDependencies](http://maven.apache.org/enforcer/enforcer-rules/banTransitiveDependencies.html) but it seems like that would catch most of this as well.

That's a totally different use case.  That actually prevents our dependencies from using their own dependencies.  (So we'd have to exclude those transitives in the `<dependency>` section.

I recognize it's currently a little unwieldy, but:
 - While I named this PR to ban transitive dependencies, what I *really* want is to restrict dependency packages to exactly the contents (which are exported) of the module descriptors of our dependencies.  This is actually even more restrictive than just the dependencies (which is good)
 - This is a package-level enforcer which is therefore precisely what I'm looking for; the other proposed solutions are dependency-level
 - I've filed an issue on the site about the duplication required by "static foo", and in version 2 that part will be a single switch (defaulting to true) which greatly simplifies it.
 - It's a little broad in including all of `java.*` rather than just the `java.base` module packages (which I'm not going to spam), but that's also a potential future improvement to import from an external file.

**Comment by dbwiddis** [comment]
I do see that this package-level functionality is in checkstyle as well, so we could perhaps go that route instead.  Seems to be roughly the same amount of work.  I'll leave this PR here while trying to tackle this in #1797.

> I think code inspection is better done using checkstyle, eg. using https://checkstyle.sourceforge.io/config_imports.html#ImportControl
as that will catch class use and isn't limited to `imports`  as noted in https://github.com/skuzzle/restrict-imports-enforcer-rule#limitation
> 
> _Originally posted by @mprins in https://github.com/oshi/oshi/issues/1794#issuecomment-979043483_

**Comment by dbwiddis** [comment]
So, I configured checkstyle using the default rules which is all well and good.  Had two ways to go:
 - use the default and add suppressions (I did this)
 - copy the default and remove the ones I don't want (started, and abandoned this as basically unmaintainable)

Now I looked at how to do this to add the ImportControl rule, and everything I read says I can't just add it to the existing default (`sun_checks.xml`), I have to basically copy the default and add to it.  What?  Seriously?

Surely I'm missing something. Importing another config and adding to it is not exactly a corner use case.

**Comment by hazendaz** [comment]
I think the sun checks are rather old.  There is a google one as well they include that works well for us.  Not too hard maintain as their jar as the file(s).  So on any new update, if something doesn't work, just compare the file from latest checkstyle with one in repo and have block comments around custom items so its clear.  Yes that is extra work and checkstyle verioning never tells you when it will hard break.

**Comment by dbwiddis** [comment]
> I think the sun checks are rather old. 

So are the sun coding conventions but I still basically use the "Sun" config in Eclipse...

> There is a google one as well they include that works well for us. 

Yeah, with code-assert I included both checks (with some suppressions).

Maybe if I'm rolling my own I'll just do the same thing here.

> Yes that is extra work and checkstyle verioning never tells you when it will hard break.

Ugh.

**Comment by dbwiddis** [comment]
> 0 It seems like a lot of work

Closing in favor of #1803, which was a lot more work :-)

**Pull request closed without merging**
