### PR TITLE
Cache maven packages to speed up workflows

### PR DESCRIPTION
**Pull request by dbwiddis**
See https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven#caching-dependencies

### CODE REVIEW

**Comment by hazendaz** [comment]
Do you know how long the caches live otherwise?

**Comment by hazendaz** [comment]
LGTM! Merged.

**Comment by dbwiddis** [comment]
Don't know anything about the caches beyond the link above.

**Comment by hazendaz** [comment]
ok thanks.  Either way this will help as pulling from sonatype seems to fail sometimes :)

**Pull request merged**
