### PR TITLE
Fixed non-static private methods by making them private

### PR DESCRIPTION
**Pull request by DennisPersaud**
Changed private methods in LinuxCentralProcessor.java to static in oshi-core package

### CODE REVIEW

**Review by dbwiddis — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution!

Unfortunately your editor is configured to use tabs instead of spaces, which effectively changed every single line in this file and makes it impossible to find and review the changes.

To quickly fix this, run `./mvnw spotless:apply` on your command line and commit the resulting changes.

For future contributions, it's good to identify the format the project uses and try to configure your editor to match it.

**Comment by DennisPersaud** [comment]
Thank you for your feedback, I have submitted my commit following your advice & will make sure to configure my editor to the correct format in the future.

**Comment by DennisPersaud** [comment]
Thank you for your feedback, I have submitted my commit following your advice & will make sure to configure my editor to the correct format for future commits.

**Review by dbwiddis — APPROVED** [review]
Thanks for fixing up the formatting! The change looks good. I'll merge as soon as CI runs!

**Comment by dbwiddis** [comment]
> Thank you for your feedback, I have submitted my commit following your advice & will make sure to configure my editor to the correct format for future commits.

For OSHI, you can find an Eclipse formatting conventions file in this directory:  https://github.com/oshi/oshi/tree/master/config

Other projects often have a similar location for an XML file.  IntelliJ can usually import Eclipse format conventions with an add-in.

**Pull request merged**
