### PR TITLE
LshwTest and DmidecodeTest for Linux Driver

### PR DESCRIPTION
**Pull request by adrian-kong**
Added some more tests for #1727

### CODE REVIEW

**Comment by adrian-kong** [comment]
i'm not sure what to check so i just checked whether they were null or non empty
also for Dmidecode#queryUUID, can't you run command "dmidecode -s system-uuid" or "dmidecode -s system-serial-number" so you don't have to parse the string itself + splitting + trimming the string?

**Comment by adrian-kong** [comment]
also, would java version be updated? the old switch statements are very ugly

**Comment by dbwiddis** [comment]
> i'm not sure what to check so i just checked whether they were null or non empty 

That's reasonable. For drivers that are documented to return null, the null is usually handled.  So we're looking to execute code that might throw some sort of exception.

> also for Dmidecode#queryUUID, can't you run command "dmidecode -s system-uuid" or "dmidecode -s system-serial-number" so you don't have to parse the string itself + splitting + trimming the string?

I haven't looked into the details of this, but I do want to comment that I am thrilled to have a second set of eyes on this code.  If those commands/switches are sufficiently standard across distributions, I'm all for improving efficiency.  I know in some cases we run one command to pull several bits of information out of it, but if there's a way to filter/shorten the return to only get the information we want without added parsing, that's fine and I welcome a fix.

**Comment by adrian-kong** [comment]
yea i searched up dmidecode before and some people use `dmidecode` -s system-serial-number` and `dmidecode -t system | grep "Serial Number"` so im not sure the difference but it looked like less splitting the string with system-serial-number.
however apparently some people get random things as output using dmidecode:
https://community.hpe.com/t5/System-Administration/How-to-get-Serial-number-in-Linux-w-o-using-dmidecode/m-p/6421524/highlight/true#M54558

**Review by dbwiddis — APPROVED** [review]

**Comment by dbwiddis** [comment]
>  however apparently some people get random things as output using dmidecode

TBH, System Serial Number is a huge headache. Lots of issues in history over it.  Linux decided they wanted to obscure that data for privacy reasons so it's not easily available without elevated permissions or other user cooperation.  Which is a win for privacy advocates, but IMO a bit aggressive when there are far easier unique ID features available.

**Comment by dbwiddis** [comment]
Uh, anyway, I'm ok merging this PR unless you wanted to change the underlying code?

**Comment by adrian-kong** [comment]
> Uh, anyway, I'm ok merging this PR unless you wanted to change the underlying code?

should i change to dmidecode -s system-serial-number and the uuid for brevity or leave as it is?

**Comment by dbwiddis** [comment]
> should i change to dmidecode -s system-serial-number and the uuid for brevity or leave as it is? it might change the output of the methods `queryUUID()` and `querySerialNumber()` since it would no longer check if the string contains the marker. i think there would be no null output instead only empty string outputs

I think I'm leaning toward leaving it as-is, mainly because these are backups and should be as robust as possible.   If running under elevated permissions, we should never get here because the sysfs command should work.
```
    private static String querySerialNumber() {
        String result = null;
        if ((result = Sysfs.queryProductSerial()) == null && (result = Dmidecode.querySerialNumber()) == null
                && (result = Lshal.querySerialNumber()) == null && (result = Lshw.querySerialNumber()) == null) {
            return Constants.UNKNOWN;
        }
        return result;
    }
```
Plus we rely on the `null` return as a fallback.

So I'm in the "If it ain't broke don't fix it" camp, particularly for "backups".

**Comment by adrian-kong** [comment]
ok epic i agree with that motto

**Comment by dbwiddis** [comment]
OK, so I merged this, but Coverity is complaining about null dereferences in the tests.

Not an overly big deal as a NPE causes a failed test, but I'm wondering if there's a way we can restructure the tests to avoid the null dereference.  Does order matter on anyOf?

**Comment by dbwiddis** [comment]
Or we can just null check the test, essentially accomplishing the "don't fail for null" goal much more cleanly.
```
if (foo != null) {
   assertThat(foo, is(something));
}
```

**Comment by adrian-kong** [comment]
> Or we can just null check the test, essentially accomplishing the "don't fail for null" goal much more cleanly.
> 
> ```
> if (foo != null) {
>    assertThat(foo, is(something));
> }
> ```

yep that's a simple and easy solution

**Comment by dbwiddis** [comment]
Do you want to handle it then? :) Here's a list:
image

**Pull request merged**
