### PR TITLE
JNA 5.15.0

### PR DESCRIPTION
**Pull request by dbwiddis**
Update JNA dependency and remove (some) temporary code.

### CODE REVIEW

**Comment by jthalmai** [comment]
The removed method IsProcessorFeaturePresent() is still called in oshi.hardware.platform.windows.WindowsCentralProcessor.java

**Comment by dbwiddis** [comment]
> The removed method IsProcessorFeaturePresent() is still called in oshi.hardware.platform.windows.WindowsCentralProcessor.java

Yep.  I tried to get rid of it but it wasn't trivial and wasn't worth the time to deal with.

The problem (if it is a problem) is that I implemented the processor features as an enum in OSHI, allowing me to iterate over `ProcessorFeature.values()`.  The JNA equivalent of the (native) enum is simply a declaration of integer constants, with the "name" only available by reflection or reading the source code.  Given the main purpose of this code is to display an actual (human readable) list of features, I decided keeping the enum was probably the best option, at least for now.

If you've got a better idea, I'm open to it.

**Comment by jthalmai** [comment]
The problem is that the other class fails with a NoSuchMethodError. If you remove a method, you should also adapt the code that calls it.

**Comment by dbwiddis** [comment]
> The problem is that the other class fails with a NoSuchMethodError. If you remove a method, you should also adapt the code that calls it.

But it's inherited.  The calling code in `WindowsCentralProcessor` calls `oshi.jna.platform.windows.Kernel32` which `extends com.sun.jna.platform.win32.Kernel32` where the method is declared.  I can see the code working correctly here (classpath): https://github.com/oshi/oshi/actions/runs/10875123481/job/30173174640#step:4:1135 and here (module path): https://github.com/oshi/oshi/actions/runs/10875123481/job/30173174640#step:4:1891

Can you be more clear how you're seeing this error?

While I agree it could be considered a "code smell" and I might want to fully qualify the superclass when it's called, I don't think it causes an exception.

**Comment by jthalmai** [comment]
In our project the call 'new oshi.SystemInfo().getHardware().getProcessor().getLogicalProcessorCount();' fails with the error.

**Comment by dbwiddis** [comment]
Do you have the latest version of JNA (specifically jna-project) as a dependency?  `NoSuchMethod` might occur if you're inheriting from an earlier version of JNA.   Use maven or gradle to show you which dependencies you are pulling in.  See https://github.com/oshi/oshi/blob/master/src/site/markdown/FAQ.md#how-do-i-resolve-jna-noclassdeffounderror-or-nosuchmethoderror-issues

**Comment by jthalmai** [comment]
Thanks, that was it. I don't know why it wasn't updated the first time as well, but now we also have the latest JNA version.

**Comment by dbwiddis** [comment]
Dependency resolution is sometimes a mystery, particularly on gradle. Maven is a bit easier to predict!

**Pull request merged**
