### PR TITLE
#1061 Fix transferTime in WindowsDisks by using 1-%Idle

### PR DESCRIPTION
**Pull request by Space2Man**
Hi,

first try at pull request. It compiles fine and uses 1 - %IdleTime to set the TransferTime.
Can you test this? I switched my system to Linux and don't have a test system at hand right now.

Thanks, Space

### CODE REVIEW

**Comment by dbwiddis** [comment]
It seems like it would work, except the default doesn't make sense (using 0 as default idle time means the disk is running 100%, it should be the opposite).  But in my testing I can't see why it's wrong the other way.  The idle and disk time always sum up to the same value, so the original method should work.

Is it WMI or performance counters giving you the odd readings in the old code?

**Comment by Space2Man** [comment]
How can I find out which method is used? What logging do I need to enable?

**Comment by dbwiddis** [comment]
Doesn't look like it's logged. You'd have to instrument the classes yourself. I'll try it tomorrow... manual WMI queries look sane, so it may be the performance counters don't read like I think they read

**Comment by Space2Man** [comment]
I tried to do some further investigations but I failed. On the system where I see the transferTime == timeStamp in my app both Get-Counter and Get-CIMInstance return value of 0 for PercentDiskTime and 100 for PercentIdleTime in PowerShell ... how do you get the PERCENTDISKTIME? Is it maybe mapped incorrectly in JNA?

I am quite lost but I am not that much into Windows :)

**Comment by Space2Man** [comment]
But I think the reason to use 1 - % Idle Time was something like this:

http://support.demandtech.com/index.php?pg=kb.page&id=47

**Comment by dbwiddis** [comment]
The "fallback" for percent disk time comes from WMI in the [Win32_PerfRawData_PerfDisk_PhysicalDisk](https://docs.microsoft.com/en-us/previous-versions/aa394308(v%3Dvs.85)) class. You can try this on your commandline:
`wmic path Win32_PerfRawData_PerfDisk_PhysicalDisk get PercentDiskTime,PercentIdleTime `

You'll notice they add up to the same number consistently.  The primary choice of data, however, is from the performance counter `\\PhysicalDisk(0 C:)\% Disk Time` (or whichever drive letter is the instance) which you can look at the processed data with the `Perfmon.exe` program, and again see that idle and disk time add up to 100%.  However, you can't see the raw numbers that go into the counter... that's possibly what OSHI is returning to you, however.

Anyway, the 1-%Idle is probably a good thing to use and I'll accept this PR, but please look at your default as noted in my first comment.

**Comment by dbwiddis** [comment]
I just tested the disk time vs. idle time on my hard drive, over 20 seconds, got:
```
9496222 94963206
9496263 94964174
...
9497756 94980229
9497787 94981199
```
The numbers sum up to elapsed milliseconds (e.g., each row sum is about 1000 more than the previous).   So this confirms subtracting idle time from elapsed time should give the correct result.

**Comment by Space2Man** [comment]
Ok, I set default to stats.timeStamp. Then transferTime should be set to 0 if nothing is returned.

**Comment by dbwiddis** [comment]
Looks good, merging.  If you want to submit the same PR against the 3.13.X branch I can update that one too.

**Pull request merged**
