### PR TITLE
Don't rely on default Charset when parsing strings

### PR DESCRIPTION
**Pull request by VedantPol**

### CODE REVIEW

**Review by dbwiddis — CHANGES_REQUESTED** [review]
As mentioned in the review on #1776, you need to add a new parameter, not replace the existing ones.   Use this String constructor:  https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#%3Cinit%3E(byte%5B%5D,int,int,java.nio.charset.Charset)

**Review by dbwiddis — APPROVED** [review]
Looks good!

**Comment by VedantPol** [comment]
Thank you for being patient with me and helping me make my first commit.

**Comment by dbwiddis** [comment]
> Thank you for being patient with me and helping me make my first commit.

If you look back at #24, and then #25, you'll see I did pretty much the same on my first commit.  Welcome to open source. :)

**Comment by dblock** [comment]
Love the concept of "first timers only" and great work @VedantPol!  

This also needs tests. Another opportunity to contribute.

**Comment by dbwiddis** [comment]
> This also needs tests. Another opportunity to contribute.

Like [this](https://github.com/oshi/oshi/blob/84a9afc849f52c88042ff1cbcc7d7d212e1b7af0/oshi-core/src/test/java/oshi/util/ParseUtilTest.java#L623)?

**Pull request merged**
