### PR TITLE
Logical cores iteration

### PR DESCRIPTION
**Pull request by J-Jimmy**
Basically copied from you comment.....
Seems kinda hacky to get a PR that way.....

### CODE REVIEW

**Comment by dbwiddis** [comment]
It's not hacky to do an bug fix!   But you need a changelog entry and probably a better title for this PR.

Also I'm going to hold off on merging this while resolving #1361 which is probably in that same iteration.  I suspect using `i` from the bitmask should be replaced by an incrementing (from 0) counter for each core instead, and it'd be nice to fix both problems in one PR.

**Comment by J-Jimmy** [comment]
I'm really not following all this code about CPU cores....
And I have no environment to test/reproduce and analyze the behaviour in order to fix it.

**Comment by dbwiddis** [comment]
I don't have a test environment either but I understand the problem well enough to describe the fix, and the user can test it.

I'll go ahead and merge this.

**Comment by dbwiddis** [comment]
Or not.  Sorry, as I dig into this I keep finding more.  The fix you did so far applies for the pre-Win7 branch of the code.

Same fix needs to be applied in `getMatchingPackage()`, `getMatchingNumaNode()`, and `getMatchingCore()`.  Everywhere you see `... mask ... & (1L << lp)) > 0` should be `... mask ... & (1L << lp)) != 0`

**Comment by dbwiddis** [comment]
And also in `getLogicalProcessorInformationEx()`

**Pull request merged**
