### PR TITLE
- fix typo

### PR DESCRIPTION
**Pull request by Space2Man**
Fix copy/paste error

### CODE REVIEW

**Comment by dbwiddis** [comment]
Completely unrelated but can you also fix [this javadoc error](https://lgtm.com/projects/g/oshi/oshi/alerts/?mode=list) while you're doing a minor commit? :)

**Comment by Space2Man** [comment]
Did not check it really but I think those two lines need to be removed only, right?

**Comment by Space2Man** [comment]
Done, check is ongoing ...

**Comment by dbwiddis** [comment]
Yep, was going to do that myself eventually, thanks for the quick action.

**Comment by dbwiddis** [comment]
This pull request **fixes 1 alert** when merging 9ba042ce92bec5fd2fb6a877dcd2c82901b03fc7 into c1197d68c21860d4b208c5c9bb37f63d3131e6f1 - [view on LGTM.com](https://lgtm.com/projects/g/oshi/oshi/rev/pr-fc4e8c62307baf8dd6031b136d7730600986886c)

**fixed alerts:**

* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
