### PR TITLE
Switch readme links for static analysis to new coordinates

### PR DESCRIPTION
**Pull request by dbwiddis**
Updating sonar badge links. (I'll have to go re-"won't fix" some of the rules, of course.)  Is there a new destination for Coverity or any other of the tools?

### CODE REVIEW

**Comment by dbwiddis** [comment]
Also I need to be [set as admin](https://sonarcloud.io/organizations/oshi-oshi/members)

**Comment by hazendaz** [comment]
@dbwiddis Looks good and you are also admin now.

**Comment by hazendaz** [comment]
Where is coverity going now?  I was unable to see.  I haven't figured out how to get oshi to show, maybe you see it?  It could be the same if that is out there.  I only can see my user account with oshi fork listed.

**Comment by dbwiddis** [comment]
Coverity goes [here](https://scan.coverity.com/projects/dblock-oshi). I'll see if I can add you as an admin there.  Alternately, if you have it set up and going to a new location, we can always just turn off that existing location.

As currently set, it triggers from travis when a build is pushed to the `coverity_scan` branch (see the .yml for branching codes).  However, that doesn't seem to work for more recent JDK's, that I haven't had time to troubleshoot.  If you have it running elsewhere on a regular schedule (on a single build), I'm happy to switch.

**Comment by hazendaz** [comment]
ok lets use that coverity for now until we can figure out how to get oshi/oshi to show up 👍

**Comment by hazendaz** [comment]
I submitted a request over there for coverity, probably goes to @dblock but maybe you have it as well.

**Pull request merged**
