### PR TITLE
defined locale in toUpperCase and toLowerCase methods

### LINKED ISSUE #2451: Audit and fix locale- and encoding- specific conversions
Coming from https://github.com/oshi/oshi/pull/2446#discussion_r1315664949

 - [x] Search for uppercase / lowercase conversions and make sure they use `Locale.ROOT`.
 - [x] Search for String format and make sure it uses `Locale.ROOT`.
 - [x] Search for String instantiation (`new String(byte[])`) that does not specify an encoding.
 - [x] Add CI checking such as checkstyle, sonar, or forbidden APIs that automates these checks in the future

### PR DESCRIPTION
**Pull request by Taz03**
fixes #2451

### CODE REVIEW

**Comment by Taz03** [comment]
should i also replace [String.format(String format, Object... args)](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object...)) with [String#format(Locale l, String format ,Object... args)](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html#format(java.util.Locale,java.lang.String,java.lang.Object...))?

**Comment by mprins** [comment]
@dbwiddis Perhaps we can add a sonar (https://rules.sonarsource.com/java/rspec-1449/) or checkstyle rule to enforce this

**Review by dbwiddis — APPROVED** [review]
LGTM! Thanks for your contribution!

**Comment by dbwiddis** [comment]
> should i also replace [String#format(String format, Object... args)](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object...)) with [String#format(Locale l, String format ,Object... args)](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html#format(java.util.Locale,java.lang.String,java.lang.Object...))?

Sure!  I'm ok if you do that in another PR.  I'll keep #2451 open to track it.

> @dbwiddis Perhaps we can add a sonar (https://rules.sonarsource.com/java/rspec-1449/) or checkstyle rule to enforce this

Yeah, I mentioned something of the sort in #2451.  I'll break that out into substeps.

**Pull request merged**
